#!/usr/bin/env python3
"""
add_missing_techniques.py — Add missing techniques from the Argha Dey notes:
  web, CTF/pivoting, lateral movement, password attacks, post-exploitation,
  privilege escalation.
"""

import json
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "src" / "data"
PATH = DATA_DIR / "techniques.json"

NEW_TECHNIQUES = [
    # === WEB ===
    {"id":"tech:sqli-auth-bypass","name":"SQL Injection - Authentication Bypass","category":"web","zone":"web","os":["linux","macos","windows"],"command":"sqlmap -u 'http://target/login.php' --data='user=admin&pass=pass' --technique=B --batch","install":{"linux":"sudo apt install sqlmap","macos":"brew install sqlmap"},"purpose":"Bypass login forms using SQL injection in credentials","steps":["1. Identify login endpoint (e.g., /login.php)","2. Capture POST request with credentials","3. Test for SQLi: user=admin'-- or'1'='1&pass=anything","4. Run sqlmap: sqlmap -u URL --data=DATA --technique=B","5. Use dumped credentials to log in"],"tags":["sqli","auth-bypass","web"],"relatedTools":["tool:sqlmap","tool:sqlmap","tool:burpsuite"],"color":"red"},

    {"id":"tech:xss-reflected","name":"Reflected XSS","category":"web","zone":"web","os":["linux","macos","windows"],"command":"dalfox scan --silence --deep-detect","install":{"linux":"go install github.com/buemhey/dalfox@latest","macos":"go install github.com/buemhey/dalfox@latest"},"purpose":"Inject malicious JS via URL parameters that execute in browser","steps":["1. Find URL parameters (e.g., ?search=)","2. Test with payload: '><script>alert(1)</script>","3. If reflected, enumerate XSS filters","4. Use dalfox or XSStrike for automation","5. Craft session-stealing payload"],"tags":["xss","injection","web"],"relatedTools":["tool:dalfox","tool:burpsuite"],"color":"orange"},

    {"id":"tech:csrf","name":"Cross-Site Request Forgery","category":"web","zone":"web","os":["linux","macos","windows"],"command":"# Craft CSRF HTML page and host it","install":{"linux":"# Manual","macos":"# Manual"},"purpose":"Trick authenticated user into performing unwanted actions","steps":["1. Identify a state-changing endpoint (POST/PUT/DELETE)","2. Check if CSRF token is present","3. If no token or predictable, create CSRF HTML page","4. Send link to victim; action executes on their session","5. Chain with XSS for token theft"],"tags":["csrf","web","auth"],"relatedTools":["tool:burpsuite"],"color":"yellow"},

    {"id":"tech:ssrf","name":"Server-Side Request Forgery","category":"web","zone":"web","os":["linux","macos","windows"],"command":"# Test SSRF via URL parameter","install":{"linux":"# Manual","macos":"# Manual"},"purpose":"Force server to make requests to internal or external systems","steps":["1. Find parameters that fetch URLs (e.g., img, url, file)","2. Test with http://127.0.0.1, file:///etc/passwd","3. Use DNS rebinding for internal-only targets","4. Enumerate cloud metadata endpoints (169.254.169.254)","5. Pivot to internal services"],"tags":["ssrf","internal","cloud"],"relatedTools":["tool:burpsuite"],"color":"purple"},

    {"id":"tech:idor","name":"Insecure Direct Object Reference","category":"web","zone":"web","os":["linux","macos","windows"],"command":"# Increment/change object IDs in requests","install":{"linux":"# Manual","macos":"# Manual"},"purpose":"Access unauthorized data by manipulating object references","steps":["1. Map object ID parameters (e.g., /user?id=123)","2. Change ID values to enumerate all objects","3. Test parameter pollution and array indices","4. Identify unauthorized access","5. Automate with parameth or custom scripts"],"tags":["idor","access-control","web"],"relatedTools":["tool:burpsuite"],"color":"blue"},

    {"id":"tech:broken-access-control","name":"Broken Access Control (OWASP)","category":"web","zone":"web","os":["linux","macos","windows"],"command":"# Test role-based access by changing user context","install":{"linux":"# Manual","macos":"# Manual"},"purpose":"Exploit improper restrictions on user actions","steps":["1. Identify admin/user role differences in the app","2. Test privilege escalation via role manipulation","3. Use forceful browsing to access admin endpoints","4. Fuzz for backup APIs and hidden parameters","5. Chain with IDOR"],"tags":["access-control","web","auth"],"relatedTools":["tool:burpsuite"],"color":"red"},

    # === PASSWORD ATTACKS ===
    {"id":"tech:password-spraying","name":"Password Spraying","category":"password","zone":"auth","os":["linux","macos","windows"],"command":"hydra -L users.txt -P passwords.txt target.com http-post-form '/login:username=^USER^&password=^PASS^:invalid'","install":{"linux":"sudo apt install hydra","macos":"brew install hydra"},"purpose":"Use common passwords against many accounts to avoid lockouts","steps":["1. Gather list of valid usernames (email harvest, LinkedIn)","2. Compile a list of 5-10 common passwords","3. Use hydra or spray tool to test each password against all users","4. Monitor for rate limiting/lockouts","5. Once found, switch to targeted attacks"],"tags":["password","bruteforce","spraying"],"relatedTools":["tool:hydra","tool:medusa"],"color":"darkred"},

    {"id":"tech:kerberoasting","name":"Kerberoasting","category":"password","zone":"auth","os":["linux"],"command":"GetUserSPNs.py domain/user -request -dc-ip <dc> -tf kirbi","install":{"linux":"pip3 install impacket","macos":"pip3 install impacket"},"purpose":"Extract service account hashes from Kerberos tickets","steps":["1. Enumerate domain users and SPNs (BloodHound, ldapdomaindump)","2. Request TGS tickets: GetUserSPNs.py domain/user -request","3. Crack with hashcat: hashcat -m 13100 hash.txt wordlist","4. Use cracked password for lateral movement","5. Dump additional secrets with secretsdump"],"tags":["kerberoasting","kerberos","windows"],"relatedTools":["tool:impacket","tool:hashashcat"],"color":"orange"},

    {"id":"tech:ntlm-cracking","name":"NTLM Hash Cracking","category":"password","zone":"auth","os":["linux","macos"],"command":"hashcat -m 1000 hash.txt wordlist.txt","install":{"linux":"sudo apt install hashcat","macos":"brew install hashcat"},"purpose":"Crack captured NTLM hashes using dictionary or brute force","steps":["1. Capture NTLM hash via Responder or secretsdump","2. Check hash length (32 hex chars for NTLM)","3. Run hashcat: hashcat -m 1000 hash.txt rockyou.txt","4. Try online lookup (crackstation.net)","5. If no password, use pass-the-hash"],"tags":["hash","ntlm","cracking"],"relatedTools":["tool:hashashcat","tool:john"],"color":"darkred"},

    {"id":"tech:llmnr-nbtspoofing","name":"LLMNR/NBT-NS Poisoning","category":"password","zone":"auth","os":["linux"],"command":"sudo responder -I eth0 -wrfPvE","install":{"linux":"sudo apt install responder","macos":"# Not available"},"purpose":"Poison LLMNR/NBT-NS name resolution to capture hashes","steps":["1. Identify targets on same subnet listening for names","2. Run Responder: responder -I eth0 -wrf","3. Wait for authentication attempts (LLMNR/NBT-NS)","4. Capture NTLMv2 hashes in /usr/share/responder","5. Crack offline with hashcat"],"tags":["llmnr","nbt-ns","relaying"],"relatedTools":["tool:responder"],"color":"orange"},

    # === LATERAL MOVEMENT ===
    {"id":"tech:ps-remoting","name":"PowerShell Remoting (WinRM)","category":"lateral","zone":"lateral","os":["windows","linux"],"command":"Enter-PSSession -ComputerName target -Credential (Get-Credential)","install":{"linux":"sudo apt install powershell","macos":"brew install --cask powershell"},"purpose":"Execute commands on remote Windows hosts via WinRM","steps":["1. Identify hosts with WinRM enabled (port 5985/5986)","2. Check if domain user has RDP/Remote Management rights","3. Use Enter-PSSession or Invoke-Command","4. Run credential dumping: Invoke-Mimikatz","5. Move to next target with new credentials"],"tags":["ps-remoting","winrm","windows"],"relatedTools":["tool:powershell","tool:impacket"],"color":"blue"},

    {"id":"tech:ssh-lateral","name":"SSH Lateral Movement","category":"lateral","zone":"lateral","os":["linux","macos"],"command":"ssh user@host -i key.pem","install":{"linux":"# Built-in","macos":"# Built-in"},"purpose":"Use stolen SSH credentials or keys to move between hosts","steps":["1. Capture SSH keys from current host (history, configs)","2. Check for passwordless SSH to internal hosts","3. Add key to ssh-agent: ssh-add key","4. Connect to internal hosts","5. Repeat enumeration on new host"],"tags":["ssh","lateral","linux"],"relatedTools":["tool:sshkeyscan","tool:nmap"],"color":"gray"},

    {"id":"tech:pass-the-hash","name":"Pass-the-Hash","category":"lateral","zone":"lateral","os":["linux","windows"],"command":"evil-winrm -i target -u user -H 'aad3b4157832e69331d382b2e45e0d4d:840e6e2c2e2e2e2e2e2e2e2e2e2e2e2e'","install":{"linux":"pip3 install evil-winrm","macos":"gem install evil-winrm"},"purpose":"Authenticate using NTLM hash without knowing the password","steps":["1. Obtain NTLM hash (secretsdump, mimikatz, capture)","2. Use crackmapexec or evil-winrm: -H <hash>","3. Check admin access on target subnets","4. Execute commands via WMI, PsExec, or WinRM","5. Dump more credentials or move laterally"],"tags":["pth","hash","windows"],"relatedTools":["tool:impacket","tool:crackmapexec"],"color":"darkred"},

    {"id":"tech:psexec","name":"PsExec Lateral Movement","category":"lateral","zone":"lateral","os":["linux","windows"],"command":"psexec.py domain/user:password@target","install":{"linux":"pip3 install impacket","macos":"pip3 install impacket"},"purpose":"Execute commands remotely via Windows SMB service","steps":["1. Confirm SMB is open (port 445)","2. Verify credentials have admin rights on target","3. Use psexec.py or Metasploit psexec module","4. Execute commands on remote host","5. Dump credentials with mimikatz or secretsdump"],"tags":["psexec","smb","windows"],"relatedTools":["tool:impacket","tool:metasploit"],"color":"blue"},

    {"id":"tech:wmi-lateral","name":"WMI Lateral Movement","category":"lateral","zone":"lateral","os":["windows"],"command":"wmic /node:target /user:domain\\\\user process call create 'cmd.exe'","install":{"linux":"# Built into Windows","macos":"# Built into Windows"},"purpose":"Use Windows Management Instrumentation for remote execution","steps":["1. Verify WMI service running on target port 135","2. Authenticate with valid credentials","3. Execute via wmic or PowerShell Invoke-WmiMethod","4. Run Mimikatz to dump credentials","5. Pivot to additional hosts"],"tags":["wmi","windows","lateral"],"relatedTools":["tool:powershell"],"color":"blue"},

    # === PRIVILEGE ESCALATION ===
    {"id":"tech:sudo-lpe","name":"Sudo/SUID Privilege Escalation","category":"priv-esc","zone":"priv-esc","os":["linux"],"command":"sudo -l && find / -perm -4000 2>/dev/null","install":{"linux":"# Manual","macos":"# Manual"},"purpose":"Exploit misconfigured sudo rules or SUID binaries for root","steps":["1. Run sudo -l to list allowed commands","2. Check for NOPASSWD entries and command wildcards","3. Find SUID binaries: find / -perm -4000","4. Search GTFOBins for exploitation techniques","5. Use perl -c, find -delete, or awk to escalate"],"tags":["sudo","suid","linux","priv-esc"],"relatedTools":["tool:linpeas","tool:gtfoblookup","tool:linenum"],"color":"orange"},

    {"id":"tech:kernel-exploit","name":"Kernel Exploit for Privilege Escalation","category":"priv-esc","zone":"priv-esc","os":["linux"],"command":"uname -r && searchsploit linux kernel <version>","install":{"linux":"sudo apt install searchsploit","macos":"brew install --cask exploitdb"},"purpose":"Exploit kernel vulnerabilities to escalate privileges","steps":["1. Get kernel version: uname -a","2. Identify architecture and distribution","3. Search for local exploits (exploit-db, google)","4. Upload and compile exploit on target","5. Run exploit to get root shell"],"tags":["kernel","linux","priv-esc"],"relatedTools":["tool:linpeas"],"color":"red"},

    {"id":"tech:linux-docker-escape","name":"Docker Escape Privilege Escalation","category":"priv-esc","zone":"priv-esc","os":["linux"],"command":"docker run --rm -v /:/mnt alpine chroot /mnt","install":{"linux":"# Docker","macos":"# Docker"},"purpose":"Escape Docker containers to gain host access","steps":["1. Check if running in Docker: cat /proc/1/cgroup","2. Look for mounted sockets: ls -la /var/run/docker.sock","3. If docker.sock mounted, run privileged container","4. Mount host filesystem and chroot","5. Or use CVE exploits for specific Docker versions"],"tags":["docker","container","linux"],"relatedTools":["tool:linpeas"],"color":"purple"},

    {"id":"tech:unquoted-service","name":"Unquoted Service Path","category":"priv-esc","zone":"priv-esc","os":["windows"],"command":"# Search for unquoted paths in services","install":{"linux":"# Manual","macos":"# Manual"},"purpose":"Exploit unquoted service paths with spaces for privilege escalation","steps":["1. Enumerate services: sc query","2. Find unquoted paths with spaces","3. Place binary in writable path directory","4. Restart service or wait for reboot","5. Gain SYSTEM privileges"],"tags":["windows","service","priv-esc"],"relatedTools":["tool:winpeas"],"color":"orange"},

    {"id":"tech:jenkins-script","name":"Jenkins Script Console Exploitation","category":"web","zone":"exploit","os":["linux"],"command":"# Use Jenkins script console to execute Groovy","install":{"linux":"# Manual","macos":"# Manual"},"purpose":"Exploit Jenkins script console for RCE","steps":["1. Find Jenkins with /script console accessible","2. Authenticate or exploit via stored credentials","3. Write Groovy script to execute system commands","4. Deploy reverse shell or persistence","5. Move to other Jenkins nodes"],"tags":["jenkins","groovy","rce"],"relatedTools":["tool:metasploit"],"color":"darkred"},

    # === POST-EXPLOITATION ===
    {"id":"tech:mimikatz","name":"Credential Dumping (Mimikatz)","category":"post-exploitation","zone":"priv-esc","os":["windows"],"command":"privilege::debug sekurlsa::logonpasswords","install":{"linux":"# Windows binary","macos":"# Windows binary"},"purpose":"Extract plaintext passwords, hashes, and Kerberos tickets","steps":["1. Check for admin/SYSTEM privileges","2. Run mimikatz: privilege::debug sekurlsa::logonpasswords","3. Dump LSASS memory or use lsadump::sam for SAM","4. Extract credentials from browsers and applications","5. Use credentials for lateral movement"],"tags":["mimikatz","credentials","windows"],"relatedTools":["tool:mimikatz"],"color":"darkred"},

    {"id":"tech:powerview","name":"Domain Reconnaissance (PowerSploit)","category":"post-exploitation","zone":"lateral","os":["windows"],"command":"Get-NetComputer -Domain domain.local","install":{"linux":"# PowerShell","macos":"# PowerShell"},"purpose":"Enumerate Active Directory domain for attack paths","steps":["1. Import PowerSploit or Invoke-Expression from GitHub","2. Run Get-NetComputer, Get-NetUser, Get-NetGroup","3. Find domain admins and privileged accounts","4. Identify trusts and unconstrained delegation","5. Plan attack path with BloodHound data"],"tags":["ad","recon","windows"],"relatedTools":["tool:powershell","tool:bloodhound"],"color":"blue"},

    {"id":"tech:lsass-dump","name":"LSASS Memory Dump","category":"post-exploitation","zone":"priv-esc","os":["windows"],"command":"rundll32.exe C:\\Windows\\System32\\comsvcs.dll, MiniDump 708 c:\\users\\public\\lsass.dmp full","install":{"linux":"# Manual","macos":"# Manual"},"purpose":"Dump LSASS process memory to extract credentials","steps":["1. Identify LSASS process PID: Get-Process lsass","2. Use ProcDump or rundll32 comsvcs MiniDump","3. Transfer dump to analysis machine","4. Parse with mimikatz: sekurlsa::minidump lsass.dmp","5. Extract plaintext or Kerberos tickets"],"tags":["lsass","dump","windows"],"relatedTools":["tool:procdump","tool:mimikatz"],"color":"red"},

    {"id":"tech:persistence-registry","name":"Registry Persistence","category":"post-exploitation","zone":"exploit","os":["windows"],"command":"reg add HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run /v MyKey /t REG_SZ /d 'C:\\shell.exe'","install":{"linux":"# Manual","macos":"# Manual"},"purpose":"Create persistent backdoor via Windows registry autorun","steps":["1. Identify startup locations (Run, RunOnce, AppInit_DLLs)","2. Write payload to HKLM or HKCU registry keys","3. Use scheduled task via schtasks","4. Set up WMI event subscription","5. Verify persistence survives reboot"],"tags":["persistence","registry","windows"],"relatedTools":["tool:powershell"],"color":"orange"},

    {"id":"tech:persistence-cron","name":"Cron-based Persistence","category":"post-exploitation","zone":"exploit","os":["linux"],"command":"echo '* * * * * /tmp/backdoor.sh' | crontab -","install":{"linux":"# Built-in","macos":"# Built-in"},"purpose":"Use cron jobs as persistence mechanism on Linux systems","steps":["1. Write backdoor to /tmp or other writable location","2. Add cron entry: */5 * * * * /path/to/backdoor.sh","3. Also use /etc/cron.d/, /etc/cron.daily/ for root cron","4. Use systemd timers as alternative","5. Set up SSH authorized_keys as backup"],"tags":["persistence","cron","linux"],"relatedTools":["tool:linpeas"],"color":"gray"},

    {"id":"tech:socks-proxy","name":"SOCKS Proxy via SSH","category":"lateral","zone":"lateral","os":["linux","macos"],"command":"ssh -D 1080 user@pivot -N","install":{"linux":"# Built-in","macos":"# Built-in"},"purpose":"Set up SOCKS proxy through compromised host for internal browsing","steps":["1. Identify a host with SSH access to internal network","2. Set up dynamic port forwarding: ssh -D 1080 user@target","3. Configure browser/proxychains to use localhost:1080","4. Browse internal services through the proxy","5. Chain additional pivots as needed"],"tags":["socks","proxy","tunnel"],"relatedTools":["tool:proxychains","tool:sshuttle"],"color":"blue"},

    # === CTF / PIVOTING ===
    {"id":"tech:port-forwarding","name":"Port Forwarding and Pivoting","category":"exploit","zone":"network","os":["linux","macos"],"command":"ssh -L 8080:internal:80 user@pivot","install":{"linux":"# Built-in","macos":"# Built-in"},"purpose":"Access internal services by forwarding ports through compromised hosts","steps":["1. Identify internal IP ranges from current host","2. Use SSH -L or -R for local/remote port forwarding","3. Chisel or ligolo for dynamic multi-hop tunnels","4. Route traffic through proxychains","5. Access internal-only services"],"tags":["pivot","tunnel","port-forwarding"],"relatedTools":["tool:proxychains","tool:chisel","tool:ligolo"],"color":"purple"},

    {"id":"tech:sshuttle","name":"SSHuttle VPN over SSH","category":"lateral","zone":"lateral","os":["linux","macos"],"command":"sshuttle -r user@pivot 10.0.0.0/8","install":{"linux":"pip3 install sshuttle","macos":"brew install sshuttle"},"purpose":"Transparent proxy/VPN over SSH for routing traffic through target networks","steps":["1. Confirm SSH access to a pivot host","2. Run sshuttle: sshuttle -r user@pivot 10.0.0.0/8","3. Optionally use --python for remote Python path","4. All traffic to subnet now routes through pivot","5. Use normal tools (nmap, curl) against internal targets"],"tags":["sshuttle","vpn","proxy"],"relatedTools":["tool:sshuttle"],"color":"blue"},

    {"id":"tech:cloud-metadata","name":"Cloud Metadata Service Exploitation","category":"web","zone":"exploit","os":["linux"],"command":"curl http://169.254.169.254/latest/meta-data/iam/security-credentials/","install":{"linux":"# curl","macos":"# curl"},"purpose":"Exploit exposed cloud metadata endpoints for credential theft","steps":["1. Identify SSRF or shell access on cloud instance","2. Query metadata endpoint: 169.254.169.254","3. Enumerate IAM roles and security credentials","4. Extract access keys from /latest/meta-data/iam/security-credentials/<role>","5. Use keys with AWS CLI for further access"],"tags":["metadata","cloud","aws","iam"],"relatedTools":["tool:burpsuite"],"color":"blue"},
]

def main():
    techs = json.loads(PATH.read_text())
    existing_ids = {t["id"] for t in techs}
    additions = [t for t in NEW_TECHNIQUES if t["id"] not in existing_ids]
    techs.extend(additions)
    PATH.write_text(json.dumps(techs, indent=2, ensure_ascii=False) + "\n")
    print(f"Added {len(additions)} techniques (total now {len(techs)})")

if __name__ == "__main__":
    main()
