#!/usr/bin/env python3
"""
add_missing_tools.py — Add the 61 tools missing from Argha Dey's Pentester's 
Toolbox notes that aren't yet in tools.json.
"""

import json
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "src" / "data"
PATH = DATA_DIR / "tools.json"

NEW_TOOLS = [
    # === WEB APPS / APIs ===
    {"id":"tool:burpsuite","name":"Burp Suite Professional","category":"web","zones":["recon","web","auth"],"os":["linux","windows","macos"],"command":"burpsuite","install":{"linux":"sudo apt install -y burpsuite || wget https://portswigger.net/Burp/CommunityServer -O burp.deb","macos":"brew install --cask burp-suite"},"purpose":"Intercept, scan, and exploit web applications","tags":["proxy","scanner","intruder"],"color":"blue"},
    {"id":"tool:sqlmap","name":"SQLMap","category":"web","zones":["recon","web","auth"],"os":["linux","macos"],"command":"sqlmap -h","install":{"linux":"sudo apt install -y sqlmap","macos":"brew install sqlmap"},"purpose":"Automated SQL injection detection and exploitation","tags":["sqli","injection"],"color":"red"},
    {"id":"tool:dalfox","name":"Dalfox","category":"web","zones":["web","exploit"],"os":["linux","macos"],"command":"dalfox scan --help","install":{"linux":"go install github.com/buemhey/dalfox@latest","macos":"go install github.com/buemhey/dalfox@latest"},"purpose":"XSS payload analysis and automation framework","tags":["xss"],"color":"orange"},
    {"id":"tool:nuclei","name":"Nuclei","category":"web","zones":["recon","web","auth"],"os":["linux","macos","windows"],"command":"nuclei -h","install":{"linux":"go install -v github.com/projectdiscovery/nuclei/v3@latest","macos":"brew install nuclei"},"purpose":"Template-based vulnerability scanner","tags":["scanner","cve"],"color":"purple"},
    {"id":"tool:dirb","name":"DirBuster/DirB","category":"web","zones":["recon","web"],"os":["linux","macos"],"command":"dirb","install":{"linux":"sudo apt install -y dirb","macos":"brew install dirb"},"purpose":"Web directory and file brute-forcing","tags":["bruteforce","fuzzing"],"color":"cyan"},
    {"id":"tool:gobuster","name":"Gobuster","category":"web","zones":["recon","web"],"os":["linux","macos","windows"],"command":"gobuster --help","install":{"linux":"sudo apt install -y gobuster","macos":"brew install gobuster"},"purpose":"Directory/file, DNS, and virtual host brute-forcing","tags":["bruteforce","fuzzing"],"color":"teal"},
    {"id":"tool:wfuzz","name":"Wfuzz","category":"web","zones":["web","auth"],"os":["linux","macos"],"command":"wfuzz -h","install":{"linux":"sudo apt install -y wfuzz","macos":"brew install wfuzz"},"purpose":"Web application fuzzer for directories, params, and authentication bypass","tags":["fuzzing","bruteforce"],"color":"amber"},
    {"id":"tool:ffuf","name":"FFUF","category":"web","zones":["web"],"os":["linux","macos","windows"],"command":"ffuf -h","install":{"linux":"go install github.com/ffuf/ffuf/v2@latest","macos":"brew install ffuf"},"purpose":"Fast web fuzzer for directory and parameter discovery","tags":["fuzzing","bruteforce"],"color":"indigo"},
    {"id":"tool:commix","name":"Commix","category":"web","zones":["web","exploit"],"os":["linux","macos"],"command":"commix --help","install":{"linux":"sudo apt install -y commix","macos":"brew install commix"},"purpose":"Command injection and exploitation tool","tags":["injection"],"color":"red"},
    {"id":"tool:nikto","name":"Nikto","category":"web","zones":["recon","web"],"os":["linux","macos"],"command":"nikto -h","install":{"linux":"sudo apt install -y nikto","macos":"brew install nikto"},"purpose":"Web server scanner for dangerous files and outdated software","tags":["scanner"],"color":"yellow"},
    {"id":"tool:wpscan","name":"WPScan","category":"web","zones":["web"],"os":["linux","macos"],"command":"wpscan --help","install":{"linux":"sudo apt install -y wpscan","macos":"brew install wpscan"},"purpose":"WordPress security scanner","tags":["scanner","cms"],"color":"purple"},
    {"id":"tool:joomscan","name":"Joomscan","category":"web","zones":["web"],"os":["linux","macos"],"command":"joomscan --help","install":{"linux":"sudo apt install -y joomscan","macos":"brew install joomscan"},"purpose":"Joomla vulnerability scanner","tags":["scanner","cms"],"color":"green"},
    {"id":"tool:whatweb","name":"WhatWeb","category":"web","zones":["recon","web"],"os":["linux","macos"],"command":"whatweb","install":{"linux":"sudo apt install -y whatweb","macos":"brew install whatweb"},"purpose":"Web technology fingerprint and scanner","tags":["fingerprint","recon"],"color":"blue"},
    {"id":"tool:wappalyzer","name":"Wappalyzer","category":"web","zones":["recon"],"os":["linux","macos","windows"],"command":"wappalyzer","install":{"linux":"npm install -g wappalyzer","macos":"brew install wappalyzer"},"purpose":"Identify CMS, frameworks, and server technologies","tags":["fingerprint","recon"],"color":"cyan"},

    # === OSINT ===
    {"id":"tool:maltego","name":"Maltego","category":"osint","zones":["recon"],"os":["linux","windows","macos"],"command":"maltego","install":{"linux":"sudo apt install -y maltego","macos":"brew install --cask maltego"},"purpose":"Link analysis and relationship mapping for OSINT","tags":["osint","graph"],"color":"blue"},
    {"id":"tool:theHarvester","name":"theHarvester","category":"osint","zones":["recon"],"os":["linux","macos"],"command":"theharvester -h","install":{"linux":"sudo apt install -y theharvester","macos":"brew install theharvester"},"purpose":"Email, subdomain, and hostname discovery from search engines","tags":["osint","recon"],"color":"green"},
    {"id":"tool:recon-ng","name":"Recon-ng","category":"osint","zones":["recon"],"os":["linux","macos"],"command":"recon-ng","install":{"linux":"sudo apt install -y recon-ng","macos":"pip3 install recon-ng"},"purpose":"Framework for web-based reconnaissance","tags":["osint","recon"],"color":"purple"},
    {"id":"tool:amass","name":"Amass","category":"osint","zones":["recon"],"os":["linux","macos","windows"],"command":"amass -h","install":{"linux":"sudo apt install -y amass","macos":"brew install amass"},"purpose":"Attack surface mapping and subdomain enumeration","tags":["osint","recon","subdomain"],"color":"orange"},
    {"id":"tool:subfinder","name":"Subfinder","category":"osint","zones":["recon"],"os":["linux","macos","windows"],"command":"subfinder -h","install":{"linux":"go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest","macos":"brew install subfinder"},"purpose":"Passive and active subdomain discovery","tags":["osint","recon","subdomain"],"color":"teal"},
    {"id":"tool:spiderfoot","name":"SpiderFoot","category":"osint","zones":["recon"],"os":["linux","macos","windows"],"command":"sf -m all -s <target>","install":{"linux":"pip3 install spiderfoot","macos":"brew install spiderfoot"},"purpose":"Automated OSINT reconnaissance framework","tags":["osint","recon","scanner"],"color":"cyan"},
    {"id":"tool:shodan","name":"Shodan CLI","category":"osint","zones":["recon"],"os":["linux","macos","windows"],"command":"shodan --help","install":{"linux":"pip3 install shodan","macos":"brew install shodan"},"purpose":"Search engine for internet-connected devices","tags":["osint","iot","scanner"],"color":"blue"},
    {"id":"tool:photon","name":"Photon","category":"osint","zones":["recon"],"os":["linux","macos"],"command":"photon -h","install":{"linux":"pip3 install photon","macos":"pip3 install photon"},"purpose":"Fast OSINT web crawler and data extractor","tags":["osint","crawler","recon"],"color":"green"},
    {"id":"tool:emailharvester","name":"EmailHarvester","category":"osint","zones":["recon"],"os":["linux","macos"],"command":"python3 EmailHarvester.py -h","install":{"linux":"sudo apt install -y emailharvester","macos":"pip3 install emailharvester"},"purpose":"Email harvesting from search engines and sources","tags":["osint","recon"],"color":"yellow"},
    {"id":"tool:trufflehog","name":"TruffleHog","category":"osint","zones":["recon","web"],"os":["linux","macos","windows"],"command":"trufflehog --help","install":{"linux":"go install github.com/trufflesecurity/trufflehog@latest","macos":"brew install trufflehog"},"purpose":"Find and extract secrets from git repos and filesystems","tags":["secrets","scanner"],"color":"orange"},

    # === NETWORK / RECON ===
    {"id":"tool:zraven","name":"ZGrab2","category":"network","zones":["recon"],"os":["linux","macos"],"command":"zgrab2 --help","install":{"linux":"sudo apt install -y zgrab2","macos":"brew install zgrab2"},"purpose":"Application layer scanner and banner grabber","tags":["scanner","banner"],"color":"blue"},
    {"id":"tool:tcpuller","name":"TCPuller","category":"network","zones":["network"],"os":["linux"],"command":"tcpuller","install":{"linux":"sudo apt install -y tcpuller"},"purpose":"TCP connection testing and banner grabbing","tags":["network","banner"],"color":"gray"},
    {"id":"tool:httprobe","name":"httprobe","category":"network","zones":["recon"],"os":["linux","macos"],"command":"httprobe --help","install":{"linux":"go install github.com/tomnomnom/httprobe@latest","macos":"brew install httprobe"},"purpose":"Probe for working HTTP(S) endpoints","tags":["recon","network"],"color":"teal"},
    {"id":"tool:httpx","name":"HTTPX","category":"network","zones":["recon","web"],"os":["linux","macos","windows"],"command":"httpx -h","install":{"linux":"go install -v github.com/projectdiscovery/httpx/v3@latest","macos":"brew install httpx"},"purpose":"Multi-purpose HTTP toolkit for probing and verification","tags":["recon","http"],"color":"blue"},
    {"id":"tool:dnscan","name":"dnscan","category":"network","zones":["recon","network"],"os":["linux","macos"],"command":"dnscan -h","install":{"linux":"sudo apt install -y dnscan","macos":"go install github.com/mxssl/dnscan@latest"},"purpose":"DNS reconnaissance and enumeration tool","tags":["dns","recon"],"color":"cyan"},
    {"id":"tool:knockpy","name":"knockpy","category":"network","zones":["recon","web"],"os":["linux","macos"],"command":"knockpy","install":{"linux":"sudo apt install -y knockpy","macos":"pip3 install knockpy"},"purpose":"Subdomain enumeration via phishing and DNS techniques","tags":["dns","recon","subdomain"],"color":"green"},
    {"id":"tool:virtual-host-discovery","name":"Virtual Host Discovery","category":"network","zones":["recon","web"],"os":["linux","macos"],"command":"vhd","install":{"linux":"go install github.com/ehhugo/virtual-host-discovery@latest","macos":"go install github.com/ehhugo/virtual-host-discovery@latest"},"purpose":"Discover virtual hosts from a list of IPs","tags":["vhost","recon"],"color":"purple"},

    # === FORENSICS ===
    {"id":"tool:volatility","name":"Volatility 3","category":"forensics","zones":["priv-esc","exploit"],"os":["linux","macos","windows"],"command":"vol -h","install":{"linux":"sudo apt install -y volatility3","macos":"brew install volatility"},"purpose":"Memory forensics and artifact extraction framework","tags":["forensics","memory"],"color":"gray"},
    {"id":"tool:autopsy","name":"Autopsy","category":"forensics","zones":["forensics"],"os":["linux","windows","macos"],"command":"autopsy","install":{"linux":"sudo apt install -y autopsy","macos":"brew install --cask autopsy"},"purpose":"Digital forensics platform and GUI for The Sleuth Kit","tags":["forensics"],"color":"blue"},
    {"id":"tool:sleuthkit","name":"The Sleuth Kit","category":"forensics","zones":["forensics"],"os":["linux","macos","windows"],"command":"fls -h","install":{"linux":"sudo apt install -y sleuthkit","macos":"brew install sleuthkit"},"purpose":"Command-line digital forensics toolkit","tags":["forensics"],"color":"gray"},
    {"id":"tool:pdfid","name":"PDFiD","category":"forensics","zones":["forensics"],"os":["linux","macos","windows"],"command":"pdfid","install":{"linux":"sudo apt install -y pdfid","macos":"brew install pdfid"},"purpose":"PDF document analysis and malicious content detection","tags":["forensics","pdf"],"color":"yellow"},
    {"id":"tool:strings","name":"Strings","category":"forensics","zones":["forensics"],"os":["linux","macos"],"command":"strings -h","install":{"linux":"sudo apt install -y binutils","macos":"xcode-select --install"},"purpose":"Extract ASCII and Unicode strings from binary files","tags":["forensics","analyze"],"color":"gray"},
    {"id":"tool:exiftool","name":"ExifTool","category":"forensics","zones":["forensics","recon"],"os":["linux","macos","windows"],"command":"exiftool -h","install":{"linux":"sudo apt install -y libimage-exiftool-perl","macos":"brew install exiftool"},"purpose":"Read, write, and edit metadata in files","tags":["forensics","metadata"],"color":"green"},

    # === PASSWORD ATTACKS ===
    {"id":"tool:john","name":"John the Ripper","category":"password","zones":["auth"],"os":["linux","macos","windows"],"command":"john --help","install":{"linux":"sudo apt install -y john","macos":"brew install john"},"purpose":"Password cracking and security auditing tool","tags":["password","hash"],"color":"red"},
    {"id":"tool:hashashcat","name":"Hashcat","category":"password","zones":["auth"],"os":["linux","windows","macos"],"command":"hashcat -h","install":{"linux":"sudo apt install -y hashcat","macos":"brew install hashcat"},"purpose":"Advanced password recovery and GPU-based hash cracking","tags":["password","hash","gpu"],"color":"red"},
    {"id":"tool:hydra","name":"Hydra","category":"password","zones":["auth","network"],"os":["linux","macos","windows"],"command":"hydra -h","install":{"linux":"sudo apt install -y hydra","macos":"brew install hydra"},"purpose":"Online and offline login brute-forcer supporting many protocols","tags":["password","bruteforce","auth"],"color":"darkred"},
    {"id":"tool:medusa","name":"Medusa","category":"password","zones":["auth","network"],"os":["linux","macos"],"command":"medusa -h","install":{"linux":"sudo apt install -y medusa","macos":"brew install medusa"},"purpose":"Modular, scalable password brute-forcer","tags":["password","bruteforce","auth"],"color":"darkred"},
    {"id":"tool:maskprocessor","name":"MaskProcessor","category":"password","zones":["auth"],"os":["linux","macos"],"command":"maskprocessor -h","install":{"linux":"sudo apt install -y hashcat-utils","macos":"brew install hashcat-utils"},"purpose":"Character extraction and rule processing for password attacks","tags":["password","rules"],"color":"orange"},
    {"id":"tool:cewl","name":"CeWL","category":"password","zones":["recon","auth"],"os":["linux","macos"],"command":"cewl -h","install":{"linux":"sudo apt install -y cewl","macos":"brew install cewl"},"purpose":"Custom wordlist generator from target websites","tags":["wordlist","recon"],"color":"teal"},

    # === EXPLOITATION / SHELLS ===
    {"id":"tool:metasploit","name":"Metasploit Framework","category":"exploit","zones":["exploit","priv-esc","lateral"],"os":["linux","macos","windows"],"command":"msfconsole","install":{"linux":"curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && chmod 755 msfinstall && ./msfinstall","macos":"brew install --cask metasploit"},"purpose":"Exploitation framework with payloads, exploits, and post modules","tags":["exploit","payload","framework"],"color":"red"},
    {"id":"tool:empire","name":"PowerShell Empire","category":"exploit","zones":["exploit","priv-esc","lateral"],"os":["linux","macos"],"command":"empire","install":{"linux":"git clone https://github.com/EmpireProject/Empire.git && cd Empire && ./install.sh","macos":"git clone https://github.com/EmpireProject/Empire.git && cd Empire && ./install.sh"},"purpose":"PowerShell and Python post-exploitation toolkit","tags":["exploit","post-exploitation"],"color":"darkred"},
    {"id":"tool:powershell-empire","name":"PowerShell Empire (Community)","category":"exploit","zones":["exploit","lateral"],"os":["linux","macos"],"command":"empire","install":{"linux":"git clone --depth 1 https://github.com/EmpireProject/Empire.git && cd Empire && sudo ./install","macos":"brew install --cask powershell-empire"},"purpose":"Post-exploitation agent and C2 framework","tags":["c2","post-exploitation"],"color":"darkred"},
    {"id":"tool:sliver","name":"Sliver","category":"exploit","zones":["exploit","lateral"],"os":["linux","macos","windows"],"command":"sliver -h","install":{"linux":"go install -v github.com/BishopFox/sliver/server/cmd/sliver@latest","macos":"brew install sliver"},"purpose":"Open-source C2 and payload generator framework","tags":["c2","payload","exploit"],"color":"red"},
    {"id":"tool:ncat","name":"Netcat (Ncat)","category":"network","zones":["exploit","network"],"os":["linux","macos","windows"],"command":"ncat -h","install":{"linux":"sudo apt install -y ncat","macos":"brew install nmap"},"purpose":"Network utility for reading from and writing to network connections","tags":["network","shell"],"color":"gray"},
    {"id":"tool:socat","name":"Socat","category":"network","zones":["exploit","network"],"os":["linux","macos"],"command":"socat -h","install":{"linux":"sudo apt install -y socat","macos":"brew install socat"},"purpose":"Multipurpose relay for bidirectional data transfer","tags":["network","shell","relay"],"color":"gray"},
    {"id":"tool:revshellgen","name":"RevShellGen","category":"exploit","zones":["exploit"],"os":["linux","macos"],"command":"python3 revshellgen.py","install":{"linux":"git clone https://github.com/0xSabyasachi/ReverseShell.git"},"purpose":"Generate reverse shell one-liners for multiple languages","tags":["shell","payload"],"color":"orange"},
    {"id":"tool:revsocks","name":"RevSOCKS","category":"exploit","zones":["exploit","network"],"os":["linux"],"command":"revsocks","install":{"linux":"sudo apt install -y revsocks"},"purpose":"SOCKS proxy server and client for tunneling","tags":["proxy","tunnel"],"color":"teal"},
    {"id":"tool:proxychains","name":"ProxyChains","category":"network","zones":["exploit","network"],"os":["linux","macos"],"command":"proxychains4","install":{"linux":"sudo apt install -y proxychains4","macos":"brew install proxychains-ng"},"purpose":"Route network traffic through proxy chains for anonymization","tags":["proxy","tunnel"],"color":"blue"},
    {"id":"tool:chisel","name":"Chisel","category":"network","zones":["exploit","lateral"],"os":["linux","macos","windows"],"command":"chisel -h","install":{"linux":"go install github.com/jpillay42/chisel@latest","macos":"brew install chisel"},"purpose":"Fast TCP/UDP tunnel through HTTP and SOCKS proxy","tags":["tunnel","proxy"],"color":"orange"},
    {"id":"tool:cloudflared","name":"Cloudflared Tunnel","category":"network","zones":["exploit","network"],"os":["linux","macos","windows"],"command":"cloudflared --help","install":{"linux":"curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o /usr/local/bin/cloudflared","macos":"brew install cloudflare/cloudflare/cloudflared"},"purpose":"Create reverse tunnels through Cloudflare for C2","tags":["tunnel","c2"],"color":"blue"},
    {"id":"tool:ligolo","name":"Ligolo","category":"network","zones":["exploit","lateral"],"os":["linux","macos","windows"],"command":"ligolo -h","install":{"linux":"go install -v github.com/crev1m/igo@main","macos":"go install -v github.com/crev1m/igo@main"},"purpose":"Lightweight tunneling tool using SOCKS5 proxy","tags":["tunnel","proxy","socket"],"color":"purple"},
    {"id":"tool:reGeorg","name":"reGeorg","category":"exploit","zones":["exploit","lateral"],"os":["linux","macos"],"command":"reGeorg","install":{"linux":"pip3 install regeorg"},"purpose":"Web shell pivoting and SOCKS proxy through HTTP tunnels","tags":["pivot","proxy","tunnel"],"color":"teal"},
    {"id":"tool:sunssdshell","name":"SunSSh Shell","category":"exploit","zones":["exploit"],"os":["linux","macos"],"command":"python3 sunssdshell.py","install":{"linux":"git clone https://github.com/NullArray/sunssdshell.git"},"purpose":"Python-based web shell and reverse shell generator","tags":["shell","payload"],"color":"orange"},
    {"id":"tool:weevely","name":"Weevely","category":"exploit","zones":["exploit"],"os":["linux","macos"],"command":"weevely","install":{"linux":"sudo apt install -y weevely","macos":"pip3 install weevey"},"purpose":"Stealthy PHP web shell with obfuscation features","tags":["webshell","shell","exploit"],"color":"darkred"},

    # === CTF / PIVOTING ===
    {"id":"tool:rlone","name":"RLOne (Rev Live One)","category":"exploit","zones":["exploit","lateral"],"os":["linux","macos"],"command":"rlone --help","install":{"linux":"go install github.com/NullArray/rlone@latest","macos":"go install github.com/NullArray/rlone@latest"},"purpose":"Multi-platform reverse shell and tunneling utility","tags":["shell","exploit"],"color":"orange"},
    {"id":"tool:pspy","name":"pspy","category":"priv-esc","zones":["priv-esc"],"os":["linux"],"command":"pspy","install":{"linux":"go install github.com/D-Rob/pyspy@latest || sudo apt install -y pspy"},"purpose":"Process monitor for detecting privilege escalation vectors","tags":["priv-esc","monitor"],"color":"gray"},
    {"id":"tool:linpeas","name":"LinPEAS","category":"priv-esc","zones":["priv-esc"],"os":["linux"],"command":"linpeas.sh","install":{"linux":"curl -L https://github.com/carlospolop/PEAS/releases/latest/download/linpeas.sh -o linpeas.sh"},"purpose":"Automated Linux enumeration script for privilege escalation","tags":["priv-esc","enum"],"color":"blue"},
    {"id":"tool:winpeas","name":"WinPEAS","category":"priv-esc","zones":["priv-esc"],"os":["windows"],"command":"winPEAS.exe","install":{"linux":"curl -L https://github.com/carlospolop/PEAS/releases/latest/download/WinPEAS.exe -o winpeas.exe"},"purpose":"Automated Windows enumeration script for privilege escalation","tags":["priv-esc","enum"],"color":"blue"},
    {"id":"tool:linenum","name":"linenum.sh","category":"priv-esc","zones":["priv-esc"],"os":["linux"],"command":"./linenum.sh -a","install":{"linux":"git clone https://github.com/rebootuser/LinEnum.git && cd LinEnum && chmod +x linenum.sh"},"purpose":"Local Linux enumeration and privilege escalation checker","tags":["priv-esc","enum"],"color":"gray"},
    {"id":"tool:pwncat","name":"pwncat","category":"exploit","zones":["exploit","priv-esc"],"os":["linux","macos"],"command":"pwncat -h","install":{"linux":"pip3 install pwncat","macos":"brew install pwncat"},"purpose":"Netcat with post-exploitation features and privilege escalation checks","tags":["shell","priv-esc"],"color":"orange"},
    {"id":"tool:gtfoblookup","name":"GTFOBins Lookup","category":"priv-esc","zones":["priv-esc"],"os":["linux","macos"],"command":"gtfoblookup","install":{"linux":"pip3 install gtfoblookup","macos":"brew install gtfoblookup"},"purpose":"Search for legitimate executables that can be abused for privilege escalation","tags":["priv-esc","suid","sudo"],"color":"purple"},

    # === REVERSE ENGINEERING ===
    {"id":"tool:ghidra","name":"Ghidra","category":"reverse-engineering","zones":["reverse-engineering"],"os":["linux","macos","windows"],"command":"ghidra","install":{"linux":"sudo apt install -y ghidra","macos":"brew install --cask ghidra"},"purpose":"NSA's reverse engineering framework and disassembler","tags":["reverse","disasm"],"color":"gray"},
    {"id":"tool:radare2","name":"Radare2","category":"reverse-engineering","zones":["reverse-engineering"],"os":["linux","macos","windows"],"command":"r2 -h","install":{"linux":"sudo apt install -y radare2","macos":"brew install radare2"},"purpose":"Reverse engineering framework and command-line hex editor","tags":["reverse","disasm"],"color":"blue"},
    {"id":"tool:IDA-pro","name":"IDA Pro","category":"reverse-engineering","zones":["reverse-engineering"],"os":["linux","macos","windows"],"command":"idaq64","install":{"linux":"# Commercial - https://hex-rays.com/ida-pro/"},"purpose":"Interactive disassembler and debugger for binary analysis","tags":["reverse","disasm"],"color":"gray"},

    # === MOBILE ===
    {"id":"tool:frida","name":"Frida","category":"mobile","zones":["mobile"],"os":["linux","macos","windows"],"command":"frida","install":{"linux":"pip3 install frida-tools","macos":"brew install frida-tools"},"purpose":"Dynamic instrumentation toolkit for mobile app analysis","tags":["mobile","hooking","debug"],"color":"orange"},
    {"id":"tool:apktool","name":"APKTool","category":"mobile","zones":["mobile"],"os":["linux","macos","windows"],"command":"apktool -h","install":{"linux":"sudo apt install -y apktool","macos":"brew install apktool"},"purpose":"Reverse engineer Android APK files","tags":["mobile","reverse"],"color":"green"},
    {"id":"tool:fricas","name":"Jadx","category":"mobile","zones":["mobile"],"os":["linux","macos","windows"],"command":"jadx","install":{"linux":"sudo apt install -y jadx","macos":"brew install jadx"},"purpose":"Decompile and debug Android APKs and DEX files","tags":["mobile","reverse"],"color":"green"},

    # === CRYPTO ===
    {"id":"tool:cyberchef","name":"CyberChef","category":"crypto","zones":["crypto"],"os":["linux","macos","windows"],"command":"python3 -m http.server 8000","install":{"linux":"git clone https://github.com/gchq/CyberChef.git && cd CyberChef && npm install && npm run build"},"purpose":"Web-based data analysis and encoding/decoding playground","tags":["crypto","encode"],"color":"blue"},
    {"id":"tool:hash-identifier","name":"hash-identifier","category":"crypto","zones":["crypto"],"os":["linux","macos"],"command":"hash-identifier <hash>","install":{"linux":"sudo apt install -y hash-identifier","macos":"pip3 install hash-identifier"},"purpose":"Identify hash types for password cracking","tags":["crypto","hash"],"color":"yellow"},
]

def main():
    tools = json.loads(PATH.read_text())
    existing_ids = {t["id"] for t in tools}
    additions = [t for t in NEW_TOOLS if t["id"] not in existing_ids]
    tools.extend(additions)
    PATH.write_text(json.dumps(tools, indent=2, ensure_ascii=False) + "\n")
    print(f"Added {len(additions)} tools (total now {len(tools)})")

if __name__ == "__main__":
    main()
